# Generated by Django 2.2.1 on 2019-06-10 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoatProfile',
            fields=[
                ('eartag_id', models.AutoField(primary_key=True, serialize=False)),
                ('eartag_color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('orange', 'Orange'), ('blue', 'Blue')], max_length=10)),
                ('nickname', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=8)),
                ('body_color', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('lost', 'Lost'), ('stolen', 'Stolen')], max_length=10)),
                ('category', models.CharField(choices=[('birth', 'Birth'), ('purchase', 'Purchase')], max_length=12)),
                ('is_castrated', models.BooleanField(default=0)),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'goat_profile',
                'ordering': ('eartag_id',),
                'get_latest_by': 'birth_date',
            },
        ),
        migrations.CreateModel(
            name='Purchase_record',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_price', models.FloatField()),
                ('purchase_date', models.DateField(auto_now=True)),
                ('purchase_from', models.CharField(max_length=250)),
                ('eartag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_goat', to='core.GoatProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goat_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_record',
                'ordering': ('purchase_id', '-purchase_date', 'eartag_id'),
                'get_latest_by': 'purchase_date',
            },
        ),
        migrations.CreateModel(
            name='Birth_record',
            fields=[
                ('birth_id', models.AutoField(primary_key=True, serialize=False)),
                ('birth_weight', models.FloatField()),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dam_profile', to='core.GoatProfile')),
                ('eartag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offspring_profile', to='core.GoatProfile')),
                ('sire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sire_profile', to='core.GoatProfile')),
            ],
            options={
                'db_table': 'birth_record',
                'ordering': ('birth_id', 'eartag_id'),
                'get_latest_by': 'birth_id',
            },
        ),
    ]
